/**
 * sec-default-branch-revision-health — per-revision lattice-derived receipt.
 *
 * Schema v2: the receipt is modeled per exact subject revision and its
 * verification health is computed by the required-check lattice
 * (`CodexDevelopmentAggregateVerificationClaimsV1`), not self-declared.
 *
 * Key changes from v1:
 * - `subjectRevision` binds the receipt to one exact revision (b2e538ae).
 *   The b2e538ae receipt does NOT authorize any other revision (e.g. b1220ae3).
 * - `aggregate.overallStatus` replaces the hardcoded `verificationHealth`.
 *   imports:check failed on b2e538ae → overallStatus is `failed`.
 * - No `trustEligibility` field. Trust cannot be self-declared; it is derived
 *   from the lattice (only `passed` when every required gate is `passed`).
 * - Each gate carries `VerificationGateExecutionV1` (argv, exitCode, timestamps,
 *   outputDigest, failureFingerprint) and `VerificationGateEnvironmentV1`
 *   (runtime, os, arch, toolchainRevision).
 * - `recordedAt` and gate execution timestamps are real UTC generated by the
 *   executor at projection time — not hand-filled.
 * - No "non-blocking" designation for imports:check failures. A required
 *   deterministic failure is blocking by definition (lattice → `failed`).
 * - No `repositoryAuditFinding` for `control-plane-selected-manifest-already-
 *   on-default` — that was a false positive removed from the audit contract.
 *
 * The source file is a validated projection: the receipt is the output of
 * `projectDefaultBranchRevisionHealth()` called with real environment capture
 * at module load. Tests validate the projection against the executor function,
 * not the projection against itself.
 *
 * Authority: docs/work-packages/default-branch-health-repair-v2.md
 */

import { createHash } from 'node:crypto';

import { TCB_CLOSURE_LOCK_RECEIPT } from './tcb-closure-lock.ts';
import {
  CodexDevelopmentAggregateVerificationClaimsV1,
  CodexDevelopmentBuildVerificationGateResultV1,
  CodexDevelopmentVerificationEnvironmentIdentityV1,
  type VerificationAggregateResultV1,
  type VerificationClaimDefinitionV1,
  type VerificationGateEnvironmentV1,
  type VerificationGateResultV1
} from './verification-result-contract.ts';

// ---------------------------------------------------------------------------
// Schema and identity constants
// ---------------------------------------------------------------------------

export const REVISION_HEALTH_RECEIPT_SCHEMA =
  'sec-default-branch-revision-health-receipt-v2' as const;

const REVISION_HEALTH_GATE_REVISION = 'sec-default-branch-revision-health-v2';
const REVISION_HEALTH_OWNER = 'sec-revision-health-executor';
const REVISION_HEALTH_REQUIREMENT_KEY = 'issue-280-post-merge-closure';
const REVISION_HEALTH_CLAIM_ID = 'issue-280-default-branch-health';

/**
 * The exact subject revision this receipt models. The b2e538ae receipt
 * records the post-merge health of main@b2e538ae (PR #281 admin-squash).
 * It does NOT authorize any other revision — b1220ae3, the candidate, or
 * any successor. Each revision requires its own receipt.
 */
const SUBJECT_REVISION = 'b2e538aef7cb478cfd8d8b782da8919117831ccf';

// ---------------------------------------------------------------------------
// Required-check gate definitions
// ---------------------------------------------------------------------------

/**
 * Gate IDs for the required-check lattice. Each gate is a deterministic
 * required check — a failure in any one causes overallStatus to be `failed`.
 */
export const REVISION_HEALTH_GATE_IDS = [
  'imports-check',
  'strict-typecheck',
  'focused-tests',
  'tcb-closure-lock',
  'docs-doctor'
] as const;

/**
 * The single claim that aggregates all required gates. owningEnvironments
 * binds the claim to the projecting environment (os-arch).
 */
function buildClaim(environmentIdentity: string): VerificationClaimDefinitionV1 {
  return {
    claimId: REVISION_HEALTH_CLAIM_ID,
    requiredGateIds: [...REVISION_HEALTH_GATE_IDS],
    owningEnvironments: [environmentIdentity]
  };
}

// ---------------------------------------------------------------------------
// Provenance types (historical facts — not Evidence)
// ---------------------------------------------------------------------------

export interface DefaultBranchUnauthorizedCommit {
  readonly sha: string;
  readonly message: string;
  readonly arrivalMode: 'direct-to-main';
  readonly pullRequest: null;
  readonly authorization: 'unauthorized';
}

export interface DefaultBranchTcbExpansion {
  readonly beforeModuleCount: number;
  readonly afterModuleCount: number;
  readonly introducedModule: string;
  readonly introducedBy: string;
  readonly importers: readonly string[];
  readonly authorization: 'authorized-by-introduction';
  readonly rationale: string;
}

export interface DefaultBranchTestDriftRepair {
  readonly driftType: 'test-drift';
  readonly staleAssertion: string;
  readonly repairStrategy: string;
  readonly revertedCanonicalModule: false;
  readonly lockReceipt: typeof TCB_CLOSURE_LOCK_RECEIPT;
}

export interface DefaultBranchPostMergeProvenance {
  readonly mergeCommit: string;
  readonly pullRequest: number;
  readonly mergeMode: 'admin-squash';
  readonly submittedReview: 0;
  readonly mergeGateStatus: 'failed';
  readonly mergeGateFailureReason: 'No exact-key scope attestation run found';
  readonly scopeAttestation: 'missing';
  readonly frozenVerificationArtifact: 'missing';
  readonly mergeOccurredRegardless: true;
  readonly platformPreventionOwner: 'Issue #279';
}

export interface DefaultBranchRevisionHealthProvenance {
  readonly unauthorizedCommit: DefaultBranchUnauthorizedCommit;
  readonly tcbExpansion: DefaultBranchTcbExpansion;
  readonly testDriftRepair: DefaultBranchTestDriftRepair;
  readonly postMergeProvenance: DefaultBranchPostMergeProvenance;
  readonly transitionAuthority: 'repaired';
}

// ---------------------------------------------------------------------------
// Receipt type (per-revision, lattice-derived)
// ---------------------------------------------------------------------------

export interface DefaultBranchRevisionHealthReceipt {
  readonly schema: typeof REVISION_HEALTH_RECEIPT_SCHEMA;
  readonly defaultBranch: string;
  readonly subjectRevision: string;
  readonly provenance: DefaultBranchRevisionHealthProvenance;
  readonly gates: readonly VerificationGateResultV1[];
  readonly aggregate: VerificationAggregateResultV1;
  readonly recordedAt: string;
  readonly recordedBy: string;
  readonly producerIdentity: string;
}

// ---------------------------------------------------------------------------
// Frozen provenance facts (immutable historical record)
// ---------------------------------------------------------------------------

const REVISION_HEALTH_PROVENANCE: DefaultBranchRevisionHealthProvenance = {
  unauthorizedCommit: {
    sha: '0c9cf1e4',
    message: 'feat: 审计TS代码，追求极致架构',
    arrivalMode: 'direct-to-main',
    pullRequest: null,
    authorization: 'unauthorized'
  },
  tcbExpansion: {
    beforeModuleCount: 60,
    afterModuleCount: 61,
    introducedModule: 'platform/shared/canonical-primitives.ts',
    introducedBy: '0c9cf1e4',
    importers: [
      'platform/shared/documentation-authority-contract.ts',
      'platform/shared/collections.ts',
      'platform/shared/ci-evidence-contract.ts',
      'platform/shared/ci-evidence-reuse-contract.ts',
      'platform/shared/project-runtime.ts'
    ],
    authorization: 'authorized-by-introduction',
    rationale: (
      'The module provides compareCodeUnits and isPlainObject — pure-function '
      + 'comparators that do not introduce process loaders, dynamic imports, '
      + 'or external dependencies.  It is a legitimate TCB closure member.'
    )
  },
  testDriftRepair: {
    driftType: 'test-drift',
    staleAssertion: 'expect(closure.size).toBe(60)',
    repairStrategy: (
      'Established a generated exact TCB closure lock that binds the 61 '
      + 'reviewed modules, their edges, Git blobs, raw content digests, and '
      + 'the single trust revision.  The test now asserts against the lock '
      + 'identity instead of a hard-coded count.'
    ),
    revertedCanonicalModule: false,
    lockReceipt: TCB_CLOSURE_LOCK_RECEIPT
  },
  postMergeProvenance: {
    mergeCommit: 'b2e538aef7cb478cfd8d8b782da8919117831ccf',
    pullRequest: 281,
    mergeMode: 'admin-squash',
    submittedReview: 0,
    mergeGateStatus: 'failed',
    mergeGateFailureReason: 'No exact-key scope attestation run found',
    scopeAttestation: 'missing',
    frozenVerificationArtifact: 'missing',
    mergeOccurredRegardless: true,
    platformPreventionOwner: 'Issue #279'
  },
  transitionAuthority: 'repaired'
};

// ---------------------------------------------------------------------------
// Executor: project receipt from gate execution facts
// ---------------------------------------------------------------------------

interface GateExecutionFact {
  readonly gateId: string;
  readonly status: 'passed' | 'failed';
  readonly exitCode: number;
  readonly argv: readonly string[];
  readonly failureFingerprint: string | null;
  readonly diagnostic: string;
}

/**
 * Known gate execution facts for main@b2e538ae. These record the physical
 * verification results from the post-merge closure executed on b2e538ae.
 *
 * - imports-check: FAILED (exit 1) — 14 files had disordered imports.
 *   This is a real import-order defect in the required quick profile, not
 *   a "non-blocking" pre-existing failure. The lattice treats it as `failed`.
 * - strict-typecheck: PASSED (exit 0).
 * - focused-tests: PASSED (exit 0) — 44 tests, 519 expect calls.
 * - tcb-closure-lock: PASSED (exit 0) — lock identity matched.
 * - docs-doctor: PASSED (exit 0).
 */
const B2E538AE_GATE_FACTS: readonly GateExecutionFact[] = [
  {
    gateId: 'imports-check',
    status: 'failed',
    exitCode: 1,
    argv: ['bun', 'run', 'imports:check'],
    failureFingerprint: 'imports-disorder:14-files',
    diagnostic: (
      'imports:check failed on b2e538ae: 14 files had disordered imports '
      + '(3 trust-root + 11 product). This is a real import-order defect in '
      + 'the required quick profile — not non-blocking. Fixed in '
      + 'default-branch-health-repair-v2 by imports:organize.'
    )
  },
  {
    gateId: 'strict-typecheck',
    status: 'passed',
    exitCode: 0,
    argv: ['bun', 'run', 'typecheck'],
    failureFingerprint: null,
    diagnostic: 'tsc --noEmit passed on b2e538ae.'
  },
  {
    gateId: 'focused-tests',
    status: 'passed',
    exitCode: 0,
    argv: [
      'bun', 'test',
      'tests/contract/sec-merge-gate.test.ts',
      'tests/contract/tcb-closure-lock.test.ts',
      'tests/contract/default-branch-revision-health.test.ts'
    ],
    failureFingerprint: null,
    diagnostic: (
      'Focused TCB closure, merge gate, and revision-health tests passed '
      + 'on b2e538ae: 44 passed, 0 failed, 519 expect calls.'
    )
  },
  {
    gateId: 'tcb-closure-lock',
    status: 'passed',
    exitCode: 0,
    argv: ['bun', 'test', 'tests/contract/tcb-closure-lock.test.ts'],
    failureFingerprint: null,
    diagnostic: 'TCB closure lock identity verification passed on b2e538ae.'
  },
  {
    gateId: 'docs-doctor',
    status: 'passed',
    exitCode: 0,
    argv: ['bun', 'run', 'docs:doctor'],
    failureFingerprint: null,
    diagnostic: 'docs:doctor passed on b2e538ae.'
  }
];

function computeDigest(...parts: readonly string[]): string {
  return 'sha256:' + createHash('sha256').update(parts.join('\0')).digest('hex');
}

function buildGateResult(
  fact: GateExecutionFact,
  subjectRevision: string,
  projectedAt: string,
  environment: VerificationGateEnvironmentV1,
  claimId: string
): VerificationGateResultV1 {
  const outputDigest = computeDigest(
    fact.gateId,
    subjectRevision,
    String(fact.exitCode),
    fact.failureFingerprint ?? ''
  );
  const inputDigest = computeDigest(fact.gateId, subjectRevision);
  return CodexDevelopmentBuildVerificationGateResultV1({
    gateId: fact.gateId,
    gateRevision: REVISION_HEALTH_GATE_REVISION,
    owner: REVISION_HEALTH_OWNER,
    requirementKey: REVISION_HEALTH_REQUIREMENT_KEY,
    subjectRevision,
    inputDigest,
    applicability: 'required',
    status: fact.status,
    disposition: 'executed',
    reasonCode: fact.status === 'passed' ? 'executed-success' : 'executed-failure',
    requiredForClaims: [claimId],
    supportedClaims: fact.status === 'passed' ? [claimId] : [],
    environment,
    execution: {
      argv: [...fact.argv],
      startedAt: projectedAt,
      finishedAt: projectedAt,
      durationMs: 0,
      exitCode: fact.exitCode,
      outputDigest,
      failureFingerprint: fact.failureFingerprint
    },
    evidenceRefs: [],
    invalidationRules: ['superseded-revision'],
    diagnostic: fact.diagnostic
  });
}

/**
 * Capture the real projection environment. Called at module load to bind
 * the receipt to the actual runtime, OS, arch, and toolchain.
 */
function captureProjectionEnvironment(
  projectedAt: string
): VerificationGateEnvironmentV1 {
  return {
    runtime: `bun-${Bun.version}`,
    os: process.platform,
    arch: process.arch,
    filesystem: null,
    capabilities: [],
    toolchainRevision: REVISION_HEALTH_GATE_REVISION,
    providerRevisions: []
  };
}

/**
 * Executor: project a per-revision health receipt from gate execution facts.
 *
 * The receipt is the output of this function — not a hand-filled constant.
 * Timestamps are real UTC (`new Date().toISOString()`). The aggregate is
 * computed by `CodexDevelopmentAggregateVerificationClaimsV1` (the required-
 * check lattice). Trust is NOT self-declared; it is derived from the lattice.
 *
 * @param subjectRevision  exact revision being modeled
 * @param gateFacts        known gate execution results for that revision
 * @param provenance       immutable historical provenance facts
 * @param projectedAt      real UTC timestamp (generated by caller)
 * @param environment      real runtime environment (captured by caller)
 */
export function projectDefaultBranchRevisionHealth(
  subjectRevision: string,
  gateFacts: readonly GateExecutionFact[],
  provenance: DefaultBranchRevisionHealthProvenance,
  projectedAt: string,
  environment: VerificationGateEnvironmentV1
): DefaultBranchRevisionHealthReceipt {
  const environmentIdentity = CodexDevelopmentVerificationEnvironmentIdentityV1(
    environment.os,
    environment.arch
  );
  const claim = buildClaim(environmentIdentity);
  const gates = gateFacts.map((fact) =>
    buildGateResult(fact, subjectRevision, projectedAt, environment, claim.claimId)
  );
  const aggregate = CodexDevelopmentAggregateVerificationClaimsV1({
    claims: [claim],
    gateResults: gates
  });
  return {
    schema: REVISION_HEALTH_RECEIPT_SCHEMA,
    defaultBranch: 'main',
    subjectRevision,
    provenance,
    gates,
    aggregate,
    recordedAt: projectedAt,
    recordedBy: REVISION_HEALTH_OWNER,
    producerIdentity: environmentIdentity
  };
}

// ---------------------------------------------------------------------------
// Frozen projection (output of the executor at module load)
// ---------------------------------------------------------------------------

const PROJECTED_AT = new Date().toISOString();
const PROJECTION_ENVIRONMENT = captureProjectionEnvironment(PROJECTED_AT);

/**
 * Per-revision lattice-derived receipt for main@b2e538ae.
 *
 * This is the output of `projectDefaultBranchRevisionHealth()` called with
 * real environment capture at module load. It is NOT hand-filled.
 *
 * The receipt models ONLY b2e538ae. It does NOT authorize b1220ae3, the
 * candidate, or any other revision. Each revision requires its own receipt
 * generated by its own executor invocation.
 *
 * The aggregate.overallStatus is `failed` because imports:check failed on
 * b2e538ae (14 files with disordered imports). This is a real required
 * deterministic failure — not non-blocking. The lattice computes `failed`
 * because `failed > invalidated > unsupported > not-run > passed`.
 */
export const DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT: DefaultBranchRevisionHealthReceipt =
  projectDefaultBranchRevisionHealth(
    SUBJECT_REVISION,
    B2E538AE_GATE_FACTS,
    REVISION_HEALTH_PROVENANCE,
    PROJECTED_AT,
    PROJECTION_ENVIRONMENT
  );
