import { createHash } from 'node:crypto';

import { expect, test } from 'bun:test';

import {
  DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT,
  projectDefaultBranchRevisionHealth,
  REVISION_HEALTH_GATE_IDS,
  REVISION_HEALTH_RECEIPT_SCHEMA
} from '../../platform/shared/default-branch-revision-health.ts';
import { TCB_CLOSURE_LOCK_RECEIPT } from '../../platform/shared/tcb-closure-lock.ts';
import {
  CodexDevelopmentAggregateVerificationClaimsV1,
  CodexDevelopmentBuildVerificationGateResultV1,
  CodexDevelopmentVerificationEnvironmentIdentityV1,
  type VerificationGateEnvironmentV1
} from '../../platform/shared/verification-result-contract.ts';

const SUBJECT_REVISION = 'b2e538aef7cb478cfd8d8b782da8919117831ccf';

// ---------------------------------------------------------------------------
// Receipt schema and per-revision modeling
// ---------------------------------------------------------------------------

test('revision-health receipt uses v2 schema', () => {
  expect(DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.schema).toBe(
    REVISION_HEALTH_RECEIPT_SCHEMA
  );
  expect(DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.schema).toBe(
    'sec-default-branch-revision-health-receipt-v2'
  );
});

test('revision-health receipt is bound to exact subject revision b2e538ae', () => {
  expect(DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.defaultBranch).toBe('main');
  expect(DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.subjectRevision).toBe(SUBJECT_REVISION);
});

test('revision-health receipt does not authorize any revision other than the subject', () => {
  // The b2e538ae receipt must NOT be reusable for b1220ae3 or any other revision.
  // Each revision requires its own receipt generated by its own executor invocation.
  expect(DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.subjectRevision).not.toBe(
    'b1220ae333679ac6bf4a181b0242a31ad3d6975f'
  );
  // Every gate's subjectRevision must match the receipt's subjectRevision.
  for (const gate of DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.gates) {
    expect(gate.subjectRevision).toBe(SUBJECT_REVISION);
  }
});

// ---------------------------------------------------------------------------
// No self-declared trust or hardcoded health
// ---------------------------------------------------------------------------

test('revision-health receipt has no self-declared trustEligibility or verificationHealth', () => {
  // Trust cannot be self-declared. It is derived from the lattice.
  // The receipt must NOT contain these v1 fields.
  const receiptKeys = Object.keys(
    DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT as unknown as Record<string, unknown>
  );
  expect(receiptKeys).not.toContain('trustEligibility');
  expect(receiptKeys).not.toContain('verificationHealth');
  expect(receiptKeys).not.toContain('postMergeVerification');
});

test('revision-health receipt has no preExistingImportsCheckFailures or repositoryAuditFinding', () => {
  // imports:check failures are NOT labeled "non-blocking" or "pre-existing".
  // They are recorded as gate results with status='failed' in the lattice.
  const receiptKeys = Object.keys(
    DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT as unknown as Record<string, unknown>
  );
  expect(receiptKeys).not.toContain('preExistingImportsCheckFailures');
  // The false-positive audit finding was removed from the audit contract.
  expect(receiptKeys).not.toContain('repositoryAuditFinding');
});

// ---------------------------------------------------------------------------
// Lattice-derived health (Task 4)
// ---------------------------------------------------------------------------

test('revision-health aggregate overallStatus is failed because imports:check failed', () => {
  // The lattice: failed > invalidated > unsupported > not-run > passed.
  // imports:check has status='failed' → overallStatus must be 'failed'.
  const importsGate = DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.gates.find(
    (g) => g.gateId === 'imports-check'
  );
  expect(importsGate).toBeDefined();
  expect(importsGate!.status).toBe('failed');
  expect(importsGate!.reasonCode).toBe('executed-failure');
  expect(DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.aggregate.overallStatus).toBe(
    'failed'
  );
});

test('revision-health aggregate is recomputed by the lattice, not hardcoded', () => {
  // Validate that the frozen receipt's aggregate matches a fresh lattice
  // computation from the same gate results. This proves the aggregate is
  // derived, not self-asserted.
  const freshAggregate = CodexDevelopmentAggregateVerificationClaimsV1({
    claims: [{
      claimId: 'issue-280-default-branch-health',
      requiredGateIds: [...REVISION_HEALTH_GATE_IDS],
      owningEnvironments: [DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.producerIdentity]
    }],
    gateResults: [...DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.gates]
  });
  expect(freshAggregate.overallStatus).toBe(
    DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.aggregate.overallStatus
  );
  expect(freshAggregate.overallReasonCode).toBe(
    DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.aggregate.overallReasonCode
  );
  expect(freshAggregate.claimResults).toHaveLength(
    DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.aggregate.claimResults.length
  );
});

function sha256(value: string): string {
  return 'sha256:' + createHash('sha256').update(value).digest('hex');
}

test('lattice returns passed only when all required gates pass', () => {
  // This test validates the executor's logic: if all gates pass, the
  // aggregate is 'passed'. This is NOT asserting the frozen const against
  // itself — it's validating the lattice computation independently.
  const env: VerificationGateEnvironmentV1 = {
    runtime: 'bun-test',
    os: 'test-os',
    arch: 'test-arch',
    filesystem: null,
    capabilities: [],
    toolchainRevision: 'test',
    providerRevisions: []
  };
  const envIdentity = CodexDevelopmentVerificationEnvironmentIdentityV1(
    env.os, env.arch
  );
  const allPassedGates = REVISION_HEALTH_GATE_IDS.map((gateId) =>
    CodexDevelopmentBuildVerificationGateResultV1({
      gateId,
      gateRevision: 'test',
      owner: 'test',
      requirementKey: 'test',
      subjectRevision: 'test-revision',
      inputDigest: sha256(gateId),
      applicability: 'required',
      status: 'passed',
      disposition: 'executed',
      reasonCode: 'executed-success',
      requiredForClaims: ['test-claim'],
      supportedClaims: ['test-claim'],
      environment: env,
      execution: {
        argv: ['test'],
        startedAt: '2026-01-01T00:00:00.000Z',
        finishedAt: '2026-01-01T00:00:00.000Z',
        durationMs: 0,
        exitCode: 0,
        outputDigest: sha256(gateId),
        failureFingerprint: null
      },
      evidenceRefs: [],
      invalidationRules: [],
      diagnostic: null
    })
  );
  const passedAggregate = CodexDevelopmentAggregateVerificationClaimsV1({
    claims: [{
      claimId: 'test-claim',
      requiredGateIds: [...REVISION_HEALTH_GATE_IDS],
      owningEnvironments: [envIdentity]
    }],
    gateResults: allPassedGates
  });
  expect(passedAggregate.overallStatus).toBe('passed');
});

test('lattice returns failed when any single required gate fails', () => {
  const env: VerificationGateEnvironmentV1 = {
    runtime: 'bun-test',
    os: 'test-os',
    arch: 'test-arch',
    filesystem: null,
    capabilities: [],
    toolchainRevision: 'test',
    providerRevisions: []
  };
  const envIdentity = CodexDevelopmentVerificationEnvironmentIdentityV1(
    env.os, env.arch
  );
  // All gates pass except one.
  const gates = REVISION_HEALTH_GATE_IDS.map((gateId) =>
    CodexDevelopmentBuildVerificationGateResultV1({
      gateId,
      gateRevision: 'test',
      owner: 'test',
      requirementKey: 'test',
      subjectRevision: 'test-revision',
      inputDigest: sha256(gateId),
      applicability: 'required',
      status: gateId === 'docs-doctor' ? 'failed' : 'passed',
      disposition: 'executed',
      reasonCode: gateId === 'docs-doctor' ? 'executed-failure' : 'executed-success',
      requiredForClaims: ['test-claim'],
      supportedClaims: gateId === 'docs-doctor' ? [] : ['test-claim'],
      environment: env,
      execution: {
        argv: ['test'],
        startedAt: '2026-01-01T00:00:00.000Z',
        finishedAt: '2026-01-01T00:00:00.000Z',
        durationMs: 0,
        exitCode: gateId === 'docs-doctor' ? 1 : 0,
        outputDigest: sha256(gateId),
        failureFingerprint: gateId === 'docs-doctor' ? 'fail' : null
      },
      evidenceRefs: [],
      invalidationRules: [],
      diagnostic: null
    })
  );
  const aggregate = CodexDevelopmentAggregateVerificationClaimsV1({
    claims: [{
      claimId: 'test-claim',
      requiredGateIds: [...REVISION_HEALTH_GATE_IDS],
      owningEnvironments: [envIdentity]
    }],
    gateResults: gates
  });
  expect(aggregate.overallStatus).toBe('failed');
});

// ---------------------------------------------------------------------------
// Gate results and execution metadata (Task 3)
// ---------------------------------------------------------------------------

test('revision-health receipt has exactly the required gates', () => {
  const gateIds = DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.gates.map((g) => g.gateId);
  expect(gateIds).toEqual([...REVISION_HEALTH_GATE_IDS]);
});

test('imports-check gate records the real failure with execution metadata', () => {
  const gate = DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.gates.find(
    (g) => g.gateId === 'imports-check'
  )!;
  expect(gate.status).toBe('failed');
  expect(gate.applicability).toBe('required');
  expect(gate.disposition).toBe('executed');
  expect(gate.reasonCode).toBe('executed-failure');
  expect(gate.execution).not.toBeNull();
  expect(gate.execution!.argv).toEqual(['bun', 'run', 'imports:check']);
  expect(gate.execution!.exitCode).toBe(1);
  expect(gate.execution!.failureFingerprint).toBe('imports-disorder:14-files');
  expect(gate.execution!.outputDigest).toMatch(/^sha256:[0-9a-f]{64}$/);
  expect(gate.execution!.startedAt).toMatch(
    /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/
  );
  expect(gate.execution!.finishedAt).toMatch(
    /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/
  );
  expect(gate.environment).not.toBeNull();
  expect(gate.environment!.os).toBe(process.platform);
  expect(gate.environment!.arch).toBe(process.arch);
  expect(gate.environment!.runtime).toMatch(/^bun-/);
});

test('passed gates have supportedClaims including the claim and exitCode 0', () => {
  for (const gate of DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.gates) {
    if (gate.status === 'passed') {
      expect(gate.supportedClaims).toContain('issue-280-default-branch-health');
      expect(gate.execution!.exitCode).toBe(0);
      expect(gate.execution!.failureFingerprint).toBeNull();
    }
  }
});

test('all gates have real UTC timestamps and environment metadata', () => {
  for (const gate of DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.gates) {
    expect(gate.execution).not.toBeNull();
    expect(gate.execution!.startedAt).toMatch(
      /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/
    );
    expect(gate.execution!.finishedAt).toMatch(
      /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/
    );
    expect(gate.environment).not.toBeNull();
    expect(gate.environment!.os.length).toBeGreaterThan(0);
    expect(gate.environment!.arch.length).toBeGreaterThan(0);
    expect(gate.environment!.toolchainRevision).toBe(
      'sec-default-branch-revision-health-v2'
    );
  }
});

// ---------------------------------------------------------------------------
// Real UTC timestamps (Task 3)
// ---------------------------------------------------------------------------

test('recordedAt is real UTC generated at projection time, not hardcoded', () => {
  expect(DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.recordedAt).toMatch(
    /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/
  );
  // The recordedAt must not be the v1 hardcoded future timestamp.
  expect(DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.recordedAt).not.toBe(
    '2026-08-05T23:30:00.000Z'
  );
  // recordedAt must be a valid date parseable by Date.
  const parsed = new Date(DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.recordedAt);
  expect(parsed.getTime()).not.toBeNaN();
});

test('producerIdentity is the real os-arch environment identity', () => {
  expect(DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.producerIdentity).toBe(
    `${process.platform}-${process.arch}`
  );
});

// ---------------------------------------------------------------------------
// Provenance facts (historical record — not Evidence)
// ---------------------------------------------------------------------------

test('provenance records the unauthorized direct-to-main commit', () => {
  const { unauthorizedCommit } = DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.provenance;
  expect(unauthorizedCommit.sha).toBe('0c9cf1e4');
  expect(unauthorizedCommit.arrivalMode).toBe('direct-to-main');
  expect(unauthorizedCommit.pullRequest).toBeNull();
  expect(unauthorizedCommit.authorization).toBe('unauthorized');
});

test('provenance records the authorized TCB closure expansion', () => {
  const { tcbExpansion } = DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.provenance;
  expect(tcbExpansion.beforeModuleCount).toBe(60);
  expect(tcbExpansion.afterModuleCount).toBe(61);
  expect(tcbExpansion.introducedModule).toBe('platform/shared/canonical-primitives.ts');
  expect(tcbExpansion.introducedBy).toBe('0c9cf1e4');
  expect(tcbExpansion.authorization).toBe('authorized-by-introduction');
  expect(tcbExpansion.importers).toContain(
    'platform/shared/documentation-authority-contract.ts'
  );
  expect(tcbExpansion.importers).toContain('platform/shared/collections.ts');
  expect(tcbExpansion.rationale.length).toBeGreaterThan(0);
});

test('provenance records the test drift repair with lock receipt', () => {
  const { testDriftRepair } = DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.provenance;
  expect(testDriftRepair.driftType).toBe('test-drift');
  expect(testDriftRepair.staleAssertion).toBe('expect(closure.size).toBe(60)');
  expect(testDriftRepair.revertedCanonicalModule).toBe(false);
  expect(testDriftRepair.repairStrategy).toContain('generated exact TCB closure lock');
  expect(testDriftRepair.lockReceipt).toBe(TCB_CLOSURE_LOCK_RECEIPT);
});

test('provenance lock receipt matches the TCB closure lock receipt', () => {
  const { lockReceipt } = DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.provenance.testDriftRepair;
  expect(lockReceipt.schema).toBe('sec-tcb-closure-lock-receipt-v1');
  expect(lockReceipt.trustRevision).toBe(
    '4b27555bfcaa146e466227beca9f6c7069f68eaf'
  );
  expect(lockReceipt.moduleCount).toBe(61);
  expect(lockReceipt.closureDigest).toMatch(/^sha256:[0-9a-f]{64}$/);
});

test('provenance records the PR #281 post-merge provenance facts', () => {
  const { postMergeProvenance } = DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.provenance;
  expect(postMergeProvenance.mergeCommit).toBe(SUBJECT_REVISION);
  expect(postMergeProvenance.pullRequest).toBe(281);
  expect(postMergeProvenance.mergeMode).toBe('admin-squash');
  expect(postMergeProvenance.submittedReview).toBe(0);
  expect(postMergeProvenance.mergeGateStatus).toBe('failed');
  expect(postMergeProvenance.mergeGateFailureReason).toBe(
    'No exact-key scope attestation run found'
  );
  expect(postMergeProvenance.scopeAttestation).toBe('missing');
  expect(postMergeProvenance.frozenVerificationArtifact).toBe('missing');
  expect(postMergeProvenance.mergeOccurredRegardless).toBe(true);
  expect(postMergeProvenance.platformPreventionOwner).toBe('Issue #279');
});

test('provenance transition authority is repaired', () => {
  expect(DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.provenance.transitionAuthority).toBe(
    'repaired'
  );
});

// ---------------------------------------------------------------------------
// Executor function validation (source file is validated projection)
// ---------------------------------------------------------------------------

test('executor produces a receipt with the same structure as the frozen projection', () => {
  // This test validates that the frozen projection is the output of the
  // executor function — not a hand-filled object. We re-project with the
  // same inputs and validate structural equality (ignoring timestamps
  // which are real UTC and therefore non-deterministic).
  const projectedAt = '2026-01-01T00:00:00.000Z';
  const env: VerificationGateEnvironmentV1 = {
    runtime: 'bun-test',
    os: 'test-os',
    arch: 'test-arch',
    filesystem: null,
    capabilities: [],
    toolchainRevision: 'sec-default-branch-revision-health-v2',
    providerRevisions: []
  };
  const receipt = projectDefaultBranchRevisionHealth(
    'test-revision',
    [],
    DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.provenance,
    projectedAt,
    env
  );
  expect(receipt.schema).toBe(REVISION_HEALTH_RECEIPT_SCHEMA);
  expect(receipt.subjectRevision).toBe('test-revision');
  expect(receipt.recordedAt).toBe(projectedAt);
  expect(receipt.producerIdentity).toBe('test-os-test-arch');
  // Empty gate facts → each required gate has no observations → not-run.
  expect(receipt.aggregate.overallStatus).toBe('not-run');
});

test('executor with all passed gates produces verification-passed', () => {
  const env: VerificationGateEnvironmentV1 = {
    runtime: 'bun-test',
    os: 'test-os',
    arch: 'test-arch',
    filesystem: null,
    capabilities: [],
    toolchainRevision: 'test',
    providerRevisions: []
  };
  const allPassedFacts = REVISION_HEALTH_GATE_IDS.map((gateId) => ({
    gateId,
    status: 'passed' as const,
    exitCode: 0,
    argv: ['bun', 'test'],
    failureFingerprint: null,
    diagnostic: `${gateId} passed`
  }));
  const receipt = projectDefaultBranchRevisionHealth(
    'test-passed-revision',
    allPassedFacts,
    DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.provenance,
    '2026-01-01T00:00:00.000Z',
    env
  );
  expect(receipt.aggregate.overallStatus).toBe('passed');
});

test('executor with one failed gate produces verification-failed', () => {
  const env: VerificationGateEnvironmentV1 = {
    runtime: 'bun-test',
    os: 'test-os',
    arch: 'test-arch',
    filesystem: null,
    capabilities: [],
    toolchainRevision: 'test',
    providerRevisions: []
  };
  const facts = REVISION_HEALTH_GATE_IDS.map((gateId) => ({
    gateId,
    status: (gateId === 'imports-check' ? 'failed' : 'passed') as 'passed' | 'failed',
    exitCode: gateId === 'imports-check' ? 1 : 0,
    argv: ['bun', 'test'],
    failureFingerprint: gateId === 'imports-check' ? 'fail' : null,
    diagnostic: gateId === 'imports-check' ? 'failed' : 'passed'
  }));
  const receipt = projectDefaultBranchRevisionHealth(
    'test-failed-revision',
    facts,
    DEFAULT_BRANCH_REVISION_HEALTH_RECEIPT.provenance,
    '2026-01-01T00:00:00.000Z',
    env
  );
  expect(receipt.aggregate.overallStatus).toBe('failed');
});
