/** Workspace Source Program public surface; owners remain split by responsibility. */
export {
  acquireExactGitTreeSnapshot as acquireExactGitTreeWorkspaceSourceSnapshot,
  acquireExactGitTreeSnapshotFromSession as acquireExactGitTreeWorkspaceSourceSnapshotFromSession, acquireStagedIndexSnapshot as acquireStagedIndexWorkspaceSourceSnapshot, acquireWorkingTreeSnapshot as acquireWorkingTreeWorkspaceSourceSnapshot, assertPhysicalWorkspaceSourceSnapshot, assertWorkspaceSourceSnapshot, compileVirtualSnapshot as compileVirtualWorkspaceSourceSnapshot, readBackStagedIndexSnapshot as readBackStagedIndexWorkspaceSourceSnapshot, requireStagedSourceSelection as requireStagedWorkspaceSourceSelection, selectStagedSnapshot as selectStagedWorkspaceSourceSnapshot, type AcquireExactGitTreeSnapshotFromSessionInput as AcquireExactGitTreeWorkspaceSourceSnapshotFromSessionInput, type AcquireExactGitTreeSnapshotInput as AcquireExactGitTreeWorkspaceSourceSnapshotInput, type AcquireStagedIndexSnapshotInput as AcquireStagedIndexWorkspaceSourceSnapshotInput, type AcquireWorkingTreeSnapshotInput as AcquireWorkingTreeWorkspaceSourceSnapshotInput, type CompileVirtualSnapshotInput as CompileVirtualWorkspaceSourceSnapshotInput, type PhysicalWorkspaceSourceSnapshot, type StagedSourceSelection as StagedWorkspaceSourceSelection, type VirtualWorkspaceSourceSnapshot, type WorkspaceSourceSnapshot, type WorkspaceSourceSnapshotSubject
} from './workspace-source-authority.ts';
export {
  compileWorkspaceSourceRevision, type WorkspaceSourceFile, type WorkspaceSourceFileMode
} from './workspace-source-content.ts';
export {
  assertTypeScriptProjectGenerationEvidence as assertWorkspaceTypeScriptProjectGenerationEvidence,
  assertTypeScriptProjectInput as assertWorkspaceTypeScriptProjectInput,
  assertTypeScriptProjectMatchesSnapshot as assertWorkspaceTypeScriptProjectInputMatchesSnapshot, compileTypeScriptProjectFactIdentity as compileWorkspaceTypeScriptProjectFactIdentity, compileTypeScriptProjectInput as compileWorkspaceTypeScriptProjectInput,
  issueTypeScriptProjectGenerationEvidence as issueWorkspaceTypeScriptProjectGenerationEvidence, projectTypeScriptProjectFactIdentity as projectWorkspaceTypeScriptProjectFactIdentity, type TypeScriptProjectFactIdentity as WorkspaceTypeScriptProjectFactIdentity, type TypeScriptProjectGenerationEvidence as WorkspaceTypeScriptProjectGenerationEvidence, type TypeScriptProjectInput as WorkspaceTypeScriptProjectInput
} from './workspace-typescript-project.ts';
