export type CiContractInspectionStepSource = Readonly<{
  id: string;
  phase: string;
  command: string;
  purpose: string;
  producesCount: number;
  produces: readonly string[];
}>;

export type CiContractInspectionSource = Readonly<{
  status: string;
  command: string;
  defaultGate: string;
  fullRuntimeGate: string;
  verificationContractRevision: string;
  executionModel: string;
  prWorkflowEvent: string;
  prDispatchType: string;
  prWorkflowStepCount: number;
  prWorkflowStepOrder: readonly string[];
  releaseWorkflowStepCount: number;
  releaseWorkflowStepOrder: readonly string[];
  prWorkflowCommandCount: number;
  prWorkflowCommands: readonly string[];
  releaseWorkflowCommandCount: number;
  releaseWorkflowCommands: readonly string[];
  mainHealthContext: string;
  mainHealthPolicyDigest: string;
  mainHealthStepCount: number;
  mainHealthStepOrder: readonly string[];
  mainHealthCommandCount: number;
  mainHealthCommands: readonly string[];
  prQuickLaneCommandCount: number;
  prQuickLaneCommands: readonly string[];
  fullLaneCommandCount: number;
  fullLaneCommands: readonly string[];
  verifyCommandCount: number;
  verifyCommands: readonly string[];
  qualityCommandCount: number;
  qualityCommands: readonly string[];
  diagnosticCommandCount: number;
  diagnosticCommands: readonly string[];
  artifactUploadCommandCount: number;
  artifactUploadCommands: readonly string[];
  artifactPathCount: number;
  artifactPaths: readonly string[];
  stepCount: number;
  steps: readonly CiContractInspectionStepSource[];
}>;
