import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { test } from 'bun:test';
import { canonicalCommitTreeInput, captureGitDevelopmentCommitContract,
  compileGitDevelopmentCommitContractDigest } from '../../src/external-capabilities/git-read/runtime/commit-contract.ts';
import { captureGitScratchIndexDelta } from '../../src/external-capabilities/git-read/runtime/scratch-input.ts';

const tree = 'a'.repeat(40), parent = 'b'.repeat(40), target = 'c'.repeat(40);
const person = () => ({ name: 'Maintainer', email: 'maintainer@example.test', date: '0 +0000' });
const commit = () => ({ tree, parents: [parent], message: 'Commit message', author: person(), committer: person(),
  repositoryRoot: path.resolve('repository'), worktreeRoot: path.resolve('repository'),
  ref: 'refs/heads/feature', expectedOld: parent, target, signing: 'disabled' as const, hooks: 'disabled' as const,
  preflightReceiptDigest: `sha256:${'d'.repeat(64)}` as const });

// Expected grammar and values below are declared independently of the capture
// functions. These tests do not issue a Git capability or assert an actual write.
test('commit capture reads each scalar once and keeps independent immutable parents and identities', () => {
  const input = commit(), reads: string[] = [];
  const view = Object.fromEntries(Object.entries(input).map(([key, value]) => [key, value]));
  for (const key of ['message', 'tree', 'target'] as const) Object.defineProperty(view, key, {
    get() { reads.push(key); return input[key]; }
  });
  const captured = captureGitDevelopmentCommitContract(view as ReturnType<typeof commit>)!;
  assert.deepEqual(reads.sort(), ['message', 'target', 'tree']);
  input.parents[0] = target; input.author.name = 'Later'; input.message = 'Later';
  assert.deepEqual(captured.parents, [parent]); assert.equal(captured.author.name, 'Maintainer');
  assert.equal(captured.message, 'Commit message');
  assert.ok(Object.isFrozen(captured)); assert.ok(Object.isFrozen(captured.parents));
  assert.ok(Object.isFrozen(captured.author)); assert.equal(Object.isFrozen(input.author), false);
});

test('commit digest preserves the prior canonical JSON domain for ordinary values', () => {
  const input = commit();
  // This explicit already-key-sorted vector is not generated by the production
  // canonicalizer or by enumerating the candidate schema.
  const expected = JSON.stringify({ author: { date: '0 +0000', email: 'maintainer@example.test', name: 'Maintainer' },
    committer: { date: '0 +0000', email: 'maintainer@example.test', name: 'Maintainer' }, expectedOld: parent,
    hooks: 'disabled', message: 'Commit message', parents: [parent], preflightReceiptDigest: `sha256:${'d'.repeat(64)}`,
    ref: 'refs/heads/feature', repositoryRoot: input.repositoryRoot, schema: 'sec-development-commit-git-contract-v1',
    signing: 'disabled', target, tree, worktreeRoot: input.worktreeRoot });
  assert.equal(compileGitDevelopmentCommitContractDigest(input), `sha256:${createHash('sha256').update(expected).digest('hex')}`);
});

test('commit policy still rejects noncanonical identities, signatures, roots and parent bindings', () => {
  for (const change of [{ signing: 'enabled' }, { hooks: 'enabled' }, { expectedOld: target }, { tree: 'a'.repeat(41) },
    { parents: [] }, { parents: [parent, target] }, { ref: 'HEAD' }, { repositoryRoot: './relative' },
    { target: target.toUpperCase() }, { preflightReceiptDigest: 'unknown' }, { message: 'a\0b' }]) {
    assert.equal(captureGitDevelopmentCommitContract({ ...commit(), ...change } as never), null);
  }
  for (const date of ['-1 +0000', '00 +0000', '0 +1460', '0 +1401', '0 +0060', '0 +1500']) {
    assert.equal(canonicalCommitTreeInput({ ...commit(), author: { ...person(), date } }), null);
  }
  for (const date of ['0 +1400', '1 -1400', '1 +0059']) {
    assert.equal(canonicalCommitTreeInput({ ...commit(), author: { ...person(), date } })?.author.date, date);
  }
});

test('a parent data slot cannot be replaced by iteration or accessor evaluation', () => {
  const input = commit(); input.parents[Symbol.iterator] = function* () { yield target; };
  assert.deepEqual(canonicalCommitTreeInput(input)?.parents, [parent]);
  Object.defineProperty(input.parents, '0', { get() { assert.fail('parent accessor'); } });
  assert.equal(canonicalCommitTreeInput(input), null);
});

test('complete scratch delta capture detaches every addition before any consumer awaits', () => {
  const input = { additions: [{ path: 'a.ts', bytes: Uint8Array.of(1) }, { path: 'b.ts', bytes: Uint8Array.of(2) }], removals: ['old.ts'] };
  const captured = captureGitScratchIndexDelta(input, 'sha1', 1000);
  input.additions[1]!.path = 'later.ts'; input.additions[1]!.bytes.fill(9); input.removals[0] = 'later.ts';
  assert.deepEqual(captured.additions.map(value => [value.path, [...value.bytes]]), [['a.ts', [1]], ['b.ts', [2]]]);
  assert.deepEqual(captured.removals, ['old.ts']); assert.ok(Object.isFrozen(captured.additions));
});

test('scratch stdin admission counts object content plus exact UTF-8 index records and removal terminators', () => {
  const input = { additions: [{ path: '好.ts', bytes: Uint8Array.of(1, 2) }], removals: ['old'] };
  for (const [format, hash] of [['sha1', 'a'.repeat(40)], ['sha256', 'a'.repeat(64)]] as const) {
    const maximum = 2 + Buffer.byteLength(`100644 ${hash}\t好.ts\0old\0`, 'utf8');
    assert.deepEqual(captureGitScratchIndexDelta(input, format, maximum).removals, ['old']);
    assert.throws(() => captureGitScratchIndexDelta(input, format, maximum - 1), RangeError);
  }
  assert.deepEqual(captureGitScratchIndexDelta({ additions: [], removals: [] }, 'sha1', 0), { additions: [], removals: [] });
});

test('scratch invalid paths, cross-list duplicates and array holes fail before returning a usable request', () => {
  for (const value of ['', '../a', '/a', './a', 'a/../b', 'a/./b', 'a\\b', 'a\0b']) {
    assert.throws(() => captureGitScratchIndexDelta({ additions: [], removals: [value] }, 'sha1', 1000));
  }
  assert.throws(() => captureGitScratchIndexDelta({ additions: [{ path: 'a', bytes: new Uint8Array() }], removals: ['a'] }, 'sha1', 1000));
  assert.throws(() => captureGitScratchIndexDelta({ additions: [], removals: new Array(1) }, 'sha1', 1000));
  const input = { additions: [], removals: ['a'] };
  input.removals[Symbol.iterator] = () => { assert.fail('custom iterator'); };
  assert.deepEqual(captureGitScratchIndexDelta(input, 'sha1', 1000).removals, ['a']);
});

test('scratch byte snapshots use the actual view and reject shared memory', () => {
  const bytes = Uint8Array.of(1, 2, 3).subarray(1);
  Object.defineProperties(bytes, { byteLength: { value: 0 }, [Symbol.iterator]: { value() { assert.fail('byte iterator'); } } });
  assert.deepEqual([...captureGitScratchIndexDelta({ additions: [{ path: 'a', bytes }], removals: [] }, 'sha1', 1000).additions[0]!.bytes], [2, 3]);
  assert.throws(() => captureGitScratchIndexDelta({ additions: [{ path: 'a', bytes: new Uint8Array(new SharedArrayBuffer(1)) }], removals: [] }, 'sha1', 1000));
});
