import { expect, test } from 'bun:test';

import { assertScopeAuthorizationCurrent, createScopeAuthorization, parseScopeAuthorization, type ScopeAuthorizationInput, type ScopeAuthorizationLiveCandidate } from '../../src/adapters/self-hosting/control/scope/authorization.ts';

const SHA = '1'.repeat(40); const TREE = '2'.repeat(40); const D = `sha256:${'a'.repeat(64)}` as const;
const SHA_B = '3'.repeat(40); const TREE_B = '4'.repeat(40); const D_B = `sha256:${'b'.repeat(64)}` as const;
function scopeInput(overrides: Partial<ScopeAuthorizationInput> = {}): ScopeAuthorizationInput { return { repository: 'sec-platform/sec', prNumber: 1, baseSha: SHA, baseTreeSha: TREE, headSha: SHA, headTreeSha: TREE, manifestPath: 'config/repository/work-packages/x.md', manifestDigest: D, proposalDigest: D, authorizedPaths: ['a.ts', 'b.ts'], sessionProposalDigest: D, actionPlanClosureDigest: D, profile: 'full', environmentDigest: D, issuer: { principalId: 'a0', role: 'trusted-base-a0', trustRevision: SHA, producerIdentity: 'trusted-scope-runtime', sourceTransport: 'trusted-base', sourceRunId: 'run-1', sourceRef: 'refs/heads/main', sourceDigest: D }, issuedAt: '2026-08-09T00:00:00.000Z', expiresAt: '2026-08-09T01:00:00.000Z', ...overrides }; }
function receipt(overrides: Partial<ScopeAuthorizationInput> = {}) { return createScopeAuthorization(scopeInput(overrides)); }
function live(value = receipt()): ScopeAuthorizationLiveCandidate { return { baseSha:value.baseSha,baseTreeSha:value.baseTreeSha,headSha:value.headSha,headTreeSha:value.headTreeSha,manifestDigest:value.manifestDigest,changedPaths:value.authorizedPaths,sessionProposalDigest:value.sessionProposalDigest,actionPlanClosureDigest:value.actionPlanClosureDigest,environmentDigest:value.environmentDigest,expectedAuthorizationRevision:value.authorizationRevision,now:value.expiresAt }; }
test('scope authorization round-trips and exact candidate matches', () => {
  const value = receipt(); expect(parseScopeAuthorization(JSON.stringify(value))).toEqual(value);
  expect(() => assertScopeAuthorizationCurrent(value, { baseSha: SHA, baseTreeSha: TREE, headSha: SHA, headTreeSha: TREE, manifestDigest: D, changedPaths: ['b.ts', 'a.ts'], sessionProposalDigest: D, actionPlanClosureDigest: D, environmentDigest: D, expectedAuthorizationRevision:value.authorizationRevision, now: '2026-08-09T00:30:00.000Z' })).not.toThrow();
});
test('write-set or manifest drift invalidates trusted proposal authorization', () => {
  const value=receipt(); expect(() => assertScopeAuthorizationCurrent(value, { baseSha: SHA, baseTreeSha: TREE, headSha: SHA, headTreeSha: TREE, manifestDigest: `sha256:${'b'.repeat(64)}`, changedPaths: ['a.ts'], sessionProposalDigest: D, actionPlanClosureDigest: D, environmentDigest: D, expectedAuthorizationRevision:value.authorizationRevision, now: '2026-08-09T00:30:00.000Z' })).toThrow('drift');
});
test('scope revision excludes downstream plan/provenance but binds authorized write scope',()=>{const a=receipt();const b=createScopeAuthorization({...a,actionPlanClosureDigest:`sha256:${'b'.repeat(64)}`,sessionProposalDigest:`sha256:${'c'.repeat(64)}`,issuer:{...a.issuer,sourceRunId:'run-2'},authorizationRevision:undefined,authorizationDigest:undefined} as never);expect(b.authorizationRevision).toBe(a.authorizationRevision);expect(b.authorizationDigest).not.toBe(a.authorizationDigest);const c=createScopeAuthorization({...a,authorizedPaths:['a.ts'],authorizationRevision:undefined,authorizationDigest:undefined} as never);expect(c.authorizationRevision).not.toBe(a.authorizationRevision)});

test('Scope exact expiry is valid and every live bound field drifts fail closed',()=>{const value=receipt();expect(()=>assertScopeAuthorizationCurrent(value,live(value))).not.toThrow();expect(()=>assertScopeAuthorizationCurrent(value,{...live(value),now:'2026-08-09T01:00:00.001Z'})).toThrow('expired');const cases:readonly [string,Partial<ScopeAuthorizationLiveCandidate>][]=[['baseSha',{baseSha:SHA_B}],['baseTreeSha',{baseTreeSha:TREE_B}],['headSha',{headSha:SHA_B}],['headTreeSha',{headTreeSha:TREE_B}],['manifestDigest',{manifestDigest:D_B}],['write set',{changedPaths:['a.ts']}],['session proposal',{sessionProposalDigest:D_B}],['action plan',{actionPlanClosureDigest:D_B}],['environment',{environmentDigest:D_B}],['revision',{expectedAuthorizationRevision:D_B}]];for(const [label,override] of cases){expect(()=>assertScopeAuthorizationCurrent(value,{...live(value),...override}),label).toThrow('drift')}});

test('Scope revision binds every upstream authorization semantic and canonicalizes path ordering',()=>{const base=receipt();const cases:readonly [string,ScopeAuthorizationInput][]=[['repository',scopeInput({repository:'sec-platform/other'})],['pr',scopeInput({prNumber:2})],['base',scopeInput({baseSha:SHA_B})],['base tree',scopeInput({baseTreeSha:TREE_B})],['head',scopeInput({headSha:SHA_B})],['head tree',scopeInput({headTreeSha:TREE_B})],['manifest path',scopeInput({manifestPath:'config/repository/work-packages/y.md'})],['manifest digest',scopeInput({manifestDigest:D_B})],['proposal',scopeInput({proposalDigest:D_B})],['profile',scopeInput({profile:'quick'})],['environment',scopeInput({environmentDigest:D_B})],['issuer principal',scopeInput({issuer:{...scopeInput().issuer,principalId:'other-a0'}})],['issuer producer',scopeInput({issuer:{...scopeInput().issuer,producerIdentity:'other-runtime'}})],['trust',scopeInput({issuer:{...scopeInput().issuer,trustRevision:SHA_B}})]];for(const [label,candidate] of cases){expect(createScopeAuthorization(candidate).authorizationRevision,label).not.toBe(base.authorizationRevision)}const reordered=receipt({authorizedPaths:['b.ts','a.ts']});expect(reordered.authorizationRevision).toBe(base.authorizationRevision);expect(()=>receipt({authorizedPaths:['a.ts','a.ts']})).toThrow('unique')});

test('Scope full provenance changes receipt digest without changing authorization revision',()=>{const base=receipt();const cases:readonly [string,Partial<ScopeAuthorizationInput>][]=[['session proposal',{sessionProposalDigest:D_B}],['action plan',{actionPlanClosureDigest:D_B}],['transport',{issuer:{...scopeInput().issuer,sourceTransport:'github-actions'}}],['source run',{issuer:{...scopeInput().issuer,sourceRunId:'run-2'}}],['source ref',{issuer:{...scopeInput().issuer,sourceRef:'refs/pull/1/head'}}],['source digest',{issuer:{...scopeInput().issuer,sourceDigest:D_B}}],['times',{issuedAt:'2026-08-09T00:10:00.000Z',expiresAt:'2026-08-09T01:10:00.000Z'}]];for(const [label,override] of cases){const candidate=receipt(override);expect(candidate.authorizationRevision,label).toBe(base.authorizationRevision);expect(candidate.authorizationDigest,label).not.toBe(base.authorizationDigest)}});

test('Scope rejects issuer/provenance, schema, extra fields, tampering, and equal expiry',()=>{for(const [label,candidate] of [['transport',scopeInput({issuer:{...scopeInput().issuer,sourceTransport:'unknown' as never}})],['source digest',scopeInput({issuer:{...scopeInput().issuer,sourceDigest:'bad' as never}})],['role',scopeInput({issuer:{...scopeInput().issuer,role:'worker' as never}})]] as const){expect(()=>createScopeAuthorization(candidate),label).toThrow()}expect(()=>receipt({expiresAt:'2026-08-09T00:00:00.000Z'})).toThrow('after issuedAt');const value=receipt();for(const candidate of [{...value,schema:'unknown'},{...value,extra:true},{...value,authorizationRevision:D_B},{...value,authorizationDigest:D_B},{...value,issuer:{...value.issuer,extra:true}}]){expect(()=>parseScopeAuthorization(JSON.stringify(candidate))).toThrow()}});
